# Generated by Django 5.2.4 on 2025-07-25 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('intensidad', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(blank=True, max_length=100)),
                ('url_preview', models.CharField(blank=True, max_length=500, null=True)),
                ('emociones', models.ManyToManyField(related_name='canciones', to='nucleo.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.emocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancionLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_emocional', models.IntegerField()),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.cancion')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.listareproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='EmocionCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.cancion')),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.emocion')),
            ],
            options={
                'unique_together': {('emocion', 'cancion')},
            },
        ),
    ]
